import React from 'react';
import { Link } from 'react-router-dom';

/**
 * TermsOfService Component
 * Placeholder page showing terms of usage for MediConnect.
 */
function TermsOfService() {
  React.useEffect(() => {
    document.title = 'MediConnect | Terms of Service';
  }, []);

  return (
    <div className="container" style={{ maxWidth: '800px', margin: '3rem auto' }}>
      <div className="card" style={{ padding: '3rem' }}>
        <h2 style={{ color: 'var(--text-primary)', marginBottom: '1.5rem' }}>Terms of Service</h2>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem', lineHeight: '1.6' }}>
          Last Updated: June 27, 2026
        </p>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem', lineHeight: '1.6' }}>
          Welcome to MediConnect. By accessing or using our platform, you agree to comply with the terms and guidelines described below.
        </p>

        <h3 style={{ marginTop: '2rem', marginBottom: '0.75rem' }}>1. Platform Purpose</h3>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem', lineHeight: '1.6' }}>
          MediConnect is an educational demonstration software application. The advice, matches, and urgency metrics generated by the AI Health Assistant are for information-matching purposes only.
        </p>

        <h3 style={{ marginTop: '2rem', marginBottom: '0.75rem' }}>2. Professional Medical Consultations</h3>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem', lineHeight: '1.6' }}>
          The platform does not provide formal medical diagnoses or prescriptions. Users must consult a licensed medical professional or check local emergency services in case of critical health situations.
        </p>

        <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '2rem', marginTop: '2.5rem', textAlign: 'center' }}>
          <Link to="/" className="btn">Back to Home</Link>
        </div>
      </div>
    </div>
  );
}

export default TermsOfService;
